kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.webwolf_server.name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.webgoat_server.name }} 
data:
  TZ: 'Europe/Amsterdam'
  WEBGOAT_HOST: {{ .Values.webgoat_server.name }}-service

