apiVersion: apps/v1
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.webgoat_server.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.webgoat_server.name }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.webgoat_server.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webgoat_server.name }} 
    spec:
      containers:
        - resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "0.5"
          name: webgoat
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          image: {{ .Values.webgoat_server.image }}
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600