apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.webwolf_server.name }}
  name: {{ .Values.webwolf_server.name }}-wolf
  namespace: {{ .Values.namespace }}
spec:
  path: /
  port:
    targetPort: 9090
  to:
    kind: Service
    name: {{ .Values.webwolf_server.name }}-service
    weight: 100
  wildcardPolicy: None
