name: "Release Pipeline"
on:
  push:
    tags:
      - test*  # todo replace with v*
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [11, 15]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean install -DskipTests
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
      - name: "Get tag name"
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: "Login to dockerhub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: false #todo enable
          tags: |
            webgoat/goatandwolf:${{ steps.tag.outputs.tag }}
          build-args: |
            webgoat_version=${{ steps.tag.outputs.tag }}
  github_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Get tag name"
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: "Create release"
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            webgoat-server/target/*.jar
            webwolf/target/*.jar
          body: |
            ## Version 8.

            ### New functionality

            - test

            ### Bug fixes

            - [#743 - Character encoding errors](https://github.com/WebGoat/WebGoat/issues/743)


            ## Contributors

            Special thanks to the following contributors providing us with a pull request:

            - Person 1
            - Person 2

            And everyone who provided feedback through Github.


            Team WebGoat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}

          draft: false
          prerelease: false